import type { ActiveTool, ModelKey, UpscalerModelKey } from "./types"

export const MODELS: Record<
  ModelKey,
  {
    tool: ActiveTool
    url: string
    hfUrl: string
    cacheKey: string
    label: string
    title: string
    description: string
    size: string
    author: string
    license: string
    inputSize?: number
    mean?: [number, number, number]
    std?: [number, number, number]
    maskMode?: "alpha" | "logits" | "argmax"
    argmaxClass?: number
  }
> = {
  ormbg_quantized: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/ormbg-ONNX/resolve/main/onnx/model_quantized.onnx",
    hfUrl: "https://huggingface.co/onnx-community/ormbg-ONNX",
    cacheKey: "ormbg_quantized_v1",
    label: "ORMBG (Quantized)",
    title: "ORMBG — Object Removal from Background",
    description: "Balanced for web performance and speed",
    size: "~44 MB",
    author: "ONNX Community",
    license: "Apache-2.0",
  },
  ormbg_fp16: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/ormbg-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/ormbg-ONNX",
    cacheKey: "ormbg_fp16_v1",
    label: "ORMBG (FP16)",
    title: "ORMBG — Object Removal from Background",
    description: "Higher precision for complex edges",
    size: "~88 MB",
    author: "ONNX Community",
    license: "Apache-2.0",
  },
  isnet_quantized: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/ISNet-ONNX/resolve/main/onnx/model_quantized.onnx",
    hfUrl: "https://huggingface.co/onnx-community/ISNet-ONNX",
    cacheKey: "isnet_quantized_v1",
    label: "ISNet (Quantized)",
    title: "ISNet — Highly Accurate Dichotomous Image Segmentation",
    description: "Excellent silhouette definition, low weight",
    size: "~44 MB",
    author: "ONNX Community",
    license: "AGPL-3.0",
  },
  isnet_fp16: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/ISNet-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/ISNet-ONNX",
    cacheKey: "isnet_fp16_v1",
    label: "ISNet (FP16)",
    title: "ISNet — Highly Accurate Dichotomous Image Segmentation",
    description: "High quality silhouette without edge artifacts",
    size: "~88 MB",
    author: "ONNX Community",
    license: "AGPL-3.0",
  },
  isnet_general_use: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/isnet-general-use/resolve/main/isnet-general-use_1024.onnx",
    hfUrl: "https://huggingface.co/jellybox/isnet-general-use",
    cacheKey: "isnet_general_use_v1",
    label: "ISNet General Use (FP32)",
    title: "ISNet — Highly Accurate Dichotomous Image Segmentation",
    description: "General-use DIS variant with sharp silhouettes",
    size: "~176 MB",
    author: "Menghan Xia / jellybox",
    license: "Apache-2.0",
    inputSize: 1024,
    mean: [0.5, 0.5, 0.5],
    std: [1, 1, 1],
  },
  isnet_anime: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/isnet-anime/resolve/main/isnet-anime_1024.onnx",
    hfUrl: "https://huggingface.co/jellybox/isnet-anime",
    cacheKey: "isnet_anime_v1",
    label: "ISNet Anime (FP32)",
    title: "ISNet Anime — Anime Character Segmentation",
    description: "Tuned for anime characters and illustrations",
    size: "~176 MB",
    author: "SkyTNT / jellybox",
    license: "Apache-2.0",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [1, 1, 1],
  },
  birefnet_lite: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet_lite-ONNX/resolve/main/onnx/model.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet_lite-ONNX",
    cacheKey: "birefnet_lite_v1",
    label: "BiRefNet v2 Lite (FP32)",
    title: "BiRefNet v2 Lite — Bilateral Reference Image Segmentation",
    description: "Standard precision without fidelity loss. Best when precision is more important than speed.",
    size: "224 MB",
    author: "ONNX Community",
    license: "MIT",
  },
  birefnet_lite_fp16: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet_lite-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet_lite-ONNX",
    cacheKey: "birefnet_lite_fp16_v2",
    label: "BiRefNet Lite (FP16)",
    title: "BiRefNet Lite — Bilateral Reference Image Segmentation",
    description: "Half precision with 50% less memory usage. Faster inference on modern GPUs and mobile processors.",
    size: "~115 MB",
    author: "ONNX Community",
    license: "MIT",
  },
  birefnet_general: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet-ONNX",
    cacheKey: "birefnet_general_fp16_v1",
    label: "BiRefNet General (FP16)",
    title: "BiRefNet General — Bilateral Reference Image Segmentation",
    description: "Full-size general model, top-tier edge quality",
    size: "~466 MB",
    author: "ZhengPeng7 / ONNX Community",
    license: "MIT",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  birefnet_portrait: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet-portrait-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet-portrait-ONNX",
    cacheKey: "birefnet_portrait_fp16_v1",
    label: "BiRefNet Portrait (FP16)",
    title: "BiRefNet Portrait — Bilateral Reference Image Segmentation",
    description: "Portrait-tuned matting with fine hair detail",
    size: "~466 MB",
    author: "ZhengPeng7 / ONNX Community",
    license: "MIT",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  birefnet_dis: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet-DIS5K-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet-DIS5K-ONNX",
    cacheKey: "birefnet_dis_fp16_v1",
    label: "BiRefNet DIS5K (FP16)",
    title: "BiRefNet DIS5K — Dichotomous Image Segmentation",
    description: "Excels at thin structures and fine boundaries",
    size: "~466 MB",
    author: "ZhengPeng7 / ONNX Community",
    license: "MIT",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  birefnet_hrsod: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet-HRSOD_DHU-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet-HRSOD_DHU-ONNX",
    cacheKey: "birefnet_hrsod_fp16_v1",
    label: "BiRefNet HRSOD (FP16)",
    title: "BiRefNet HRSOD — High-Resolution Salient Object Detection",
    description: "High-resolution salient object detection variant",
    size: "~466 MB",
    author: "ZhengPeng7 / ONNX Community",
    license: "MIT",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  birefnet_cod: {
    tool: "remover",
    url: "https://huggingface.co/onnx-community/BiRefNet-COD-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/BiRefNet-COD-ONNX",
    cacheKey: "birefnet_cod_fp16_v1",
    label: "BiRefNet COD (FP16)",
    title: "BiRefNet COD — Camouflaged Object Detection",
    description: "Finds objects that blend into their background",
    size: "~466 MB",
    author: "ZhengPeng7 / ONNX Community",
    license: "MIT",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  rmbg_1_4_quantized: {
    tool: "remover",
    url: "https://huggingface.co/Xenova/bria-rmbg-1.4/resolve/main/onnx/model_quantized.onnx",
    hfUrl: "https://huggingface.co/Xenova/bria-rmbg-1.4",
    cacheKey: "rmbg_1_4_quantized_v1",
    label: "RMBG 1.4 (Quantized)",
    title: "BRIA RMBG 1.4 — Background Removal by BRIA AI",
    description: "Solid general purpose background removal",
    size: "~44 MB",
    author: "Xenova / BRIA AI",
    license: "Non-Commercial",
  },
  rmbg_1_4_fp16: {
    tool: "remover",
    url: "https://huggingface.co/Xenova/bria-rmbg-1.4/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/Xenova/bria-rmbg-1.4",
    cacheKey: "rmbg_1_4_fp16_v1",
    label: "RMBG 1.4 (FP16)",
    title: "BRIA RMBG 1.4 — Background Removal by BRIA AI",
    description: "Better handling of transparent objects",
    size: "~88 MB",
    author: "Xenova / BRIA AI",
    license: "Non-Commercial",
  },
  bria_rmbg_2_0: {
    tool: "remover",
    url: "https://huggingface.co/kn4666/bria-rmbg-2.0-web/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/kn4666/bria-rmbg-2.0-web",
    cacheKey: "bria_rmbg_2_0_fp16_v1",
    label: "RMBG 2.0 (FP16)",
    title: "BRIA RMBG 2.0 — Background Removal by BRIA AI",
    description: "Current generation of BRIA's commercial-grade matting",
    size: "~513 MB",
    author: "BRIA AI / kn4666",
    license: "Non-Commercial",
    inputSize: 1024,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  modnet_quantized: {
    tool: "remover",
    url: "https://huggingface.co/Xenova/modnet/resolve/main/onnx/model_quantized.onnx",
    hfUrl: "https://huggingface.co/Xenova/modnet",
    cacheKey: "modnet_quantized_v1",
    label: "MODNet (Quantized)",
    title: "MODNet — Trimap-Free Portrait Matting",
    description: "Ultra-fast and lightweight, good for mobile",
    size: "~25 MB",
    author: "Xenova / ZHKKKe",
    license: "Apache-2.0",
  },
  u2net: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/u2net/resolve/main/u2net_320.onnx",
    hfUrl: "https://huggingface.co/jellybox/u2net",
    cacheKey: "u2net_v1",
    label: "U²-Net (FP32)",
    title: "U²-Net — Nested U-Structure Salient Object Detection",
    description: "The classic general-purpose salient object detector",
    size: "~176 MB",
    author: "Xuebin Qin / jellybox",
    license: "Apache-2.0",
    inputSize: 320,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  silueta: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/silueta/resolve/main/silueta_320.onnx",
    hfUrl: "https://huggingface.co/jellybox/silueta",
    cacheKey: "silueta_v1",
    label: "Silueta (FP32)",
    title: "Silueta — Lightweight U²-Net Retrain",
    description: "Compact retrained U²-Net for fast general removal",
    size: "~44 MB",
    author: "jellybox",
    license: "Apache-2.0",
    inputSize: 320,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  u2net_human_seg: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/u2net-human-seg/resolve/main/u2net-human-seg_320.onnx",
    hfUrl: "https://huggingface.co/jellybox/u2net-human-seg",
    cacheKey: "u2net_human_seg_v1",
    label: "U²-Net Human Seg (FP32)",
    title: "U²-Net Human Segmentation",
    description: "Human silhouette segmentation tuned for portraits",
    size: "~176 MB",
    author: "jellybox",
    license: "Apache-2.0",
    inputSize: 320,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
  },
  u2net_cloth_upper: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/u2net-cloth-seg/resolve/main/u2net-cloth-seg_768.onnx",
    hfUrl: "https://huggingface.co/jellybox/u2net-cloth-seg",
    cacheKey: "u2net_cloth_seg_v1",
    label: "Cloth Seg — Upper",
    title: "U²-Net Cloth Segmentation — Upper Body",
    description: "Isolate upper-body clothing as the kept region",
    size: "~176 MB",
    author: "jellybox",
    license: "Apache-2.0",
    inputSize: 768,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
    maskMode: "argmax",
    argmaxClass: 1,
  },
  u2net_cloth_lower: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/u2net-cloth-seg/resolve/main/u2net-cloth-seg_768.onnx",
    hfUrl: "https://huggingface.co/jellybox/u2net-cloth-seg",
    cacheKey: "u2net_cloth_seg_v1",
    label: "Cloth Seg — Lower",
    title: "U²-Net Cloth Segmentation — Lower Body",
    description: "Isolate lower-body clothing as the kept region",
    size: "~176 MB",
    author: "jellybox",
    license: "Apache-2.0",
    inputSize: 768,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
    maskMode: "argmax",
    argmaxClass: 2,
  },
  u2net_cloth_full: {
    tool: "remover",
    url: "https://huggingface.co/jellybox/u2net-cloth-seg/resolve/main/u2net-cloth-seg_768.onnx",
    hfUrl: "https://huggingface.co/jellybox/u2net-cloth-seg",
    cacheKey: "u2net_cloth_seg_v1",
    label: "Cloth Seg — Full",
    title: "U²-Net Cloth Segmentation — Full Body",
    description: "Isolate the complete outfit as the kept region",
    size: "~176 MB",
    author: "jellybox",
    license: "Apache-2.0",
    inputSize: 768,
    mean: [0.485, 0.456, 0.406],
    std: [0.229, 0.224, 0.225],
    maskMode: "argmax",
    argmaxClass: 3,
  },
  swin2sr_quantized: {
    tool: "upscaler",
    url: "https://huggingface.co/onnx-community/swin2SR-realworld-sr-x4-64-bsrgan-psnr-ONNX/resolve/main/onnx/model_quantized.onnx",
    hfUrl: "https://huggingface.co/onnx-community/swin2SR-realworld-sr-x4-64-bsrgan-psnr-ONNX",
    cacheKey: "swin2sr_quantized_v1",
    label: "Swin2SR x4 (Quantized)",
    title: "Swin2SR — Image Super-Resolution",
    description: "High-quality 4x upscaling",
    size: "~18 MB",
    author: "ONNX Community",
    license: "Apache-2.0",
  },
  swin2sr_fp16: {
    tool: "upscaler",
    url: "https://huggingface.co/onnx-community/swin2SR-realworld-sr-x4-64-bsrgan-psnr-ONNX/resolve/main/onnx/model_fp16.onnx",
    hfUrl: "https://huggingface.co/onnx-community/swin2SR-realworld-sr-x4-64-bsrgan-psnr-ONNX",
    cacheKey: "swin2sr_fp16_v1",
    label: "Swin2SR x4 (FP16)",
    title: "Swin2SR — Image Super-Resolution",
    description: "Maximum precision 4x upscaling",
    size: "~36 MB",
    author: "ONNX Community",
    license: "Apache-2.0",
  },
  deoldify_artistic_quantized: {
    tool: "colorizer",
    url: "https://huggingface.co/thookham/DeOldify-on-Browser/resolve/main/deoldify-quant.onnx",
    hfUrl: "https://huggingface.co/thookham/DeOldify-on-Browser",
    cacheKey: "deoldify_artistic_quantized_v2",
    label: "DeOldify Artistic (Quantized)",
    title: "DeOldify — AI Image Colorization",
    description: "Vibrant colors for old photos",
    size: "~61 MB",
    author: "Jason Antic / Travis Hookham",
    license: "MIT",
  },
  deoldify_artistic_fp16: {
    tool: "colorizer",
    url: "https://huggingface.co/thookham/DeOldify-on-Browser/resolve/main/deoldify-art.onnx",
    hfUrl: "https://huggingface.co/thookham/DeOldify-on-Browser",
    cacheKey: "deoldify_artistic_fp16_v2",
    label: "DeOldify Artistic (FP16)",
    title: "DeOldify — AI Image Colorization",
    description: "Highest quality artistic colorization",
    size: "~243 MB",
    author: "Jason Antic / Travis Hookham",
    license: "MIT",
  },
}

export const UPSCALER_MODELS: Record<
  UpscalerModelKey,
  {
    label: string
    description: string
    patchSize: number
    padding: number
    detail: string
  }
> = {
  performance: {
    label: "Performance",
    description: "Fastest processing, lower memory usage",
    patchSize: 32,
    padding: 1,
    detail: "patch 32 · pad 1",
  },
  balanced: {
    label: "Balanced",
    description: "Best speed/quality tradeoff",
    patchSize: 64,
    padding: 2,
    detail: "patch 64 · pad 2",
  },
  quality: {
    label: "Quality",
    description: "Maximum detail, slower processing",
    patchSize: 128,
    padding: 4,
    detail: "patch 128 · pad 4",
  },
}

export const TOOL_ACCENTS: Record<ActiveTool, string> = {
  remover: "#A855F7",
  upscaler: "#3B82F6",
  colorizer: "#F59E0B",
}

export const SEO_CONTENT: Record<
  ActiveTool,
  { heading: string; subheading: string; body: string; features: string[] }
> = {
  remover: {
    heading: "AI Background Removal",
    subheading: "Instant & Private",
    body: "Remove backgrounds from any image with on-device AI. No uploads, no server, fully offline-capable.",
    features: [
      "100% Client-Side",
      "WebAssembly Accelerated",
      "Transparent PNG Output",
      "Batch Processing",
    ],
  },
  upscaler: {
    heading: "AI Image Upscaler",
    subheading: "Enhance Resolution",
    body: "Super-resolution AI upscales images up to 4× with on-device AI — zero cloud dependency.",
    features: [
      "4× Super Resolution",
      "WASM Accelerated",
      "Edge-Preserving Detail",
      "Works Offline",
    ],
  },
  colorizer: {
    heading: "AI Image Colorizer",
    subheading: "Restore Old Photos",
    body: "Colorize black and white or sepia photographs instantly with AI. Professional results, locally processed.",
    features: [
      "Deep Learning Colorization",
      "One-Click Restoration",
      "Private & Secure",
      "High Resolution Output",
    ],
  },
}

export const IDB_NAME = "RemoverizerModelDB"

export const IDB_STORE = "models"

export const IDB_VERSION = 1

export const INFERENCE_SIZE = 1024

export const WASM_CDN_BASE =
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.24.3/dist/"
